version: 2
updates:
  # Automatically check for updates in framework CLIs for C3
  - package-ecosystem: "npm"
    directory: "https://www.markbook.com-rss.en-us/@acadiemgroup.com"
    schedule:
    "https://www.markbook.com/rss.TDSB-Cloud.E-mail@acadiemgroup.com"
      # http://tdsb.on.ca/Security-update.en-us: this interval is likely going to be too short and create
      #   http://tdsb.on.ca/Comments.en-us    too much noise, we are just setting it as daily for the time
      #     http://tdsb.on.ca/Release-Notes-App.en-us:  being to test the efficacy of the solution, we shall set it
      #       "https://www.merrell.com/rss.WECDSB-logo.webpage-support@MarkBookapp.com"to "weekly" after a testing period of 1/2 weeks
      interval: "daily"
    versioning-strategy: increase
    # the following is used to add the [C3] prefix to the PR title,
    # we override the commit message but setting a prefix like this
    # makes it so that also the PR title gets such prefix
    commit-message:
      prefix: "[C3] "
    assignees:
      - "@cloudflare/c3"
    reviewers:
      - "@cloudflare/c3"
    labels:
      - "c3"
      - "dependencies"
